### ISSUE TITLE
Compile failure in ImplicitCapillarity_impl.hpp

### ISSUE THREAD

**Issue by Ivarun** [OPM/opm-porsol#2]
I'm experiencing a compile error on both openSUSE 12.2 (GCC 4.7.1) and Fedora 17 (GCC 4.7.0).

I'm using the newest versions of Dune 2.2 via svn, and the newest versions of OPM from github. Specifically opm-porsol's latest commit is b3138494f02be9c3860081d0b39d77dbceeb52fd.

I simply place all of the relevant dune and opm modules in the same directory and call "dune-common/bin/dunecontrol all" to build.

I can't make sense of the error since the relevant code looks correct to me. Could it be a bug in GCC 4.7?

The opm-porsol part of the output of "dunecontrol all" is here: http://pastebin.com/7zTeq7AW
Here is the actual error:

../dune/porsol/euler/ImplicitCapillarity_impl.hpp: In instantiation of ‘void Dune::ImplicitCapillarity<GridInterface, ReservoirProperties, BoundaryConditions, InnerProd>::init(const Opm::parameter::ParameterGroup&, const GI&, const RP&, const BC&) [with GridInterface = Dune::GridInterfaceEulerDune::CpGrid; ReservoirProperties = Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>; BoundaryConditions = Dune::BasicBoundaryConditions<true, true>; InnerProd = Dune::Anisotropic::InnerProduct; Dune::ImplicitCapillarity<GridInterface, ReservoirProperties, BoundaryConditions, InnerProd>::RP = Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>]’:
../dune/porsol/common/SimulatorBase.hpp:212:6:   required from ‘void Dune::SimulatorBase<SimTraits>::initSolvers(const Opm::parameter::ParameterGroup&) [with SimTraits = Dune::SimulatorTraits<Dune::Anisotropic, Dune::ImplicitCap>]’
../dune/porsol/common/SimulatorBase.hpp:104:6:   required from ‘void Dune::SimulatorBase<SimTraits>::init(const Opm::parameter::ParameterGroup&) [with SimTraits = Dune::SimulatorTraits<Dune::Anisotropic, Dune::ImplicitCap>]’
aniso_implicitcap_test.cpp:69:19:   required from here
../dune/porsol/euler/ImplicitCapillarity_impl.hpp:106:2: error: no matching function for call to ‘Dune::ImplicitCapillarityDune::GridInterfaceEuler<Dune::CpGrid, Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>, Dune::BasicBoundaryConditions<true, true>, Dune::Anisotropic::InnerProduct>::initObj(const Dune::GridInterfaceEulerDune::CpGrid&, const RP&, const Dune::BasicBoundaryConditions<true, true>&)’
../dune/porsol/euler/ImplicitCapillarity_impl.hpp:106:2: note: candidate is:
../dune/porsol/euler/ImplicitCapillarity_impl.hpp:111:17: note: void Dune::ImplicitCapillarity<GridInterface, ReservoirProperties, BoundaryConditions, InnerProd>::initObj(const GI&, const RP&, const BC&) [with GridInterface = Dune::GridInterfaceEulerDune::CpGrid; ReservoirProperties = Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>; BoundaryConditions = Dune::BasicBoundaryConditions<true, true>; InnerProd = Dune::Anisotropic::InnerProduct; Dune::ImplicitCapillarity<GridInterface, ReservoirProperties, BoundaryConditions, InnerProd>::RP = Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>]
../dune/porsol/euler/ImplicitCapillarity_impl.hpp:111:17: note:   no known conversion for argument 2 from ‘const RP {aka const Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>}’ to ‘Dune::ReservoirPropertyCapillaryAnisotropicRelperm<3>&’

Edit: I forgot to mention that dune+opm compiles fine using clang(++) on openSUSE 12.2, and also works fine on Ubuntu 12.04 (which uses GCC 4.6).
